name: Publish Package to GitHub Packages

on:
  push:
    branches:
      - main
    paths:
      - 'lcdp-app/packages/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Authenticate to GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Publish package
        run: |
          if [[ $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^package/') ]]; then
            echo "Changes detected in 'package' directory, publishing package..."
            npm publish --registry=https://npm.pkg.github.com/
          else
            echo "No changes detected in 'package' directory, skipping publish."
          fi
